### PR TITLE
docs: bump golang version

### LINKED ISSUE #75: Go version spec
Thanks for your work on this, it is very nice.

When building with Go 1.7, `time.Until` is not yet supported and the build fails as follows:

```/go/src/github.com/sourcegraph/checkup/tlschecker.go:171: undefined: time.Until```

Docs indicate that 1.7+ is required, but given age of 1.8 and that `checkup` builds fine with 1.8+, it seemed like an appropriate approach would be to update the docs. PR forthcoming with those minor changes.

If instead you'd prefer that I fix the 1.7 specific build issue, I am happy to tackle that instead.

### PR DESCRIPTION
**Pull request by schvin**
bump to 1.8 and increase chance of success for simpler docker example.

Fixes #75

### CODE REVIEW

**Comment by mholt** [comment]
Excellent, thank you!
