### ISSUE TITLE
Go version spec

### ISSUE THREAD

**Issue by schvin** [sourcegraph/checkup#75]
Thanks for your work on this, it is very nice.

When building with Go 1.7, `time.Until` is not yet supported and the build fails as follows:

```/go/src/github.com/sourcegraph/checkup/tlschecker.go:171: undefined: time.Until```

Docs indicate that 1.7+ is required, but given age of 1.8 and that `checkup` builds fine with 1.8+, it seemed like an appropriate approach would be to update the docs. PR forthcoming with those minor changes.

If instead you'd prefer that I fix the 1.7 specific build issue, I am happy to tackle that instead.
